// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;
// kIsWeb,
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
    // if (kIsWeb) {
    //   throw UnsupportedError(
    //     'DefaultFirebaseOptions have not been configured for web - '
    //     'you can reconfigure this by running the FlutterFire CLI again.',
    //   );
    // }
    // ignore: missing_enum_constant_in_switch
    // switch (defaultTargetPlatform) {
    //   case TargetPlatform.android:
    //     return android;
    //   case TargetPlatform.iOS:
    //     throw UnsupportedError(
    //       'DefaultFirebaseOptions have not been configured for ios - '
    //       'you can reconfigure this by running the FlutterFire CLI again.',
    //     );
    //   case TargetPlatform.macOS:
    //     throw UnsupportedError(
    //       'DefaultFirebaseOptions have not been configured for macos - '
    //       'you can reconfigure this by running the FlutterFire CLI again.',
    //     );
    // }
    //
    // throw UnsupportedError(
    //   'DefaultFirebaseOptions are not supported for this platform.',
    // );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmKp18XLPbfJkIRf7Oy37a7uhvnE_yMok',
    appId: '1:913461078382:android:d5e39fda12278b9411b97f',
    messagingSenderId: '913461078382',
    projectId: 'aceteam-18b6b',
    databaseURL: 'https://aceteam-18b6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aceteam-18b6b.appspot.com',
  );
}
