/// Flutter icons SmartHomeIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SmartHomeIcon
///      fonts:
///       - asset: fonts/SmartHomeIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SmartHomeIcon {
  SmartHomeIcon._();

  static const _kFontFam = 'SmartHomeIcon';
  static const String? _kFontPkg = null;

  static const IconData colorize = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
